settings:
  default_form_open_message: 'This form has not yet been opened to submissions.'
  default_submit_button_label: Submit
  default_reset_button_label: Palauta
  default_delete_button_label: Poista
  default_form_confidential_message: 'This form is confidential. You must <a href="[site:login-url]/logout?destination=[current-page:url:relative]">Log out</a> to submit it.'
  default_wizard_start_label: Start
  default_wizard_confirmation_label: Complete
  default_wizard_toggle_show_label: 'Show all'
  default_wizard_toggle_hide_label: 'Hide all'
  default_preview_next_button_label: Preview
  default_preview_label: Preview
  default_draft_button_label: 'Save Draft'
  default_draft_saved_message: 'Submission saved. You may return to this form later and it will restore the current values.'
  default_confirmation_message: 'New submission added to [webform:title].'
  dialog_options:
    narrow:
      title: Narrow
    normal:
      title: Normal
    wide:
      title: Wide
element:
  default_more_title: Lisää
  default_section_title_tag: h2
