settings:
  default_form_open_message: 'Tätä lomaketta ei ole vielä avattu lähetyksille.'
  default_submit_button_label: Submit
  default_reset_button_label: Palauta
  default_delete_button_label: Poista
  default_form_confidential_message: 'Tämä lomake on luottamuksellinen. Sinun täytyy <a href="[site:login-url]/logout?destination=[current-page:url:relative]">kirjautua ulos</a> lähettääksesi se.'
  default_form_access_denied_message: 'Please login to access this form.'
  default_wizard_start_label: Alkaa
  default_wizard_confirmation_label: Valmis
  default_wizard_toggle_show_label: 'Näytä kaikki'
  default_wizard_toggle_hide_label: 'Piilota kaikki'
  default_preview_next_button_label: Preview
  default_preview_label: Preview
  default_draft_button_label: 'Tallenna keskeneräinen'
  default_draft_saved_message: 'Tiedot tallennettu. Voit palata tähän lomakkeeseen myöhemmin ja palauttaa nykyiset tiedot.'
  default_confirmation_message: 'Lisätty uusi lähetys lomakkeelle [webform:title].'
  default_submission_access_denied_message: 'Please login to access this submission.'
  dialog_options:
    narrow:
      title: Narrow
    normal:
      title: Normaali
    wide:
      title: Wide
element:
  default_more_title: Lisää
  default_section_title_tag: h2
file:
  file_private_redirect_message: 'Please login to access the uploaded file.'
