settings:
  default_submit_button_label: Submit
  default_reset_button_label: بازنشانی
  default_delete_button_label: حذف
  default_form_access_denied_message: 'Please login to access this form.'
  default_wizard_next_button_label: 'بعدی >'
  default_wizard_confirmation_label: کامل
  default_wizard_toggle_show_label: 'نمایش همه'
  default_preview_next_button_label: Preview
  default_preview_label: Preview
  default_submission_access_denied_message: 'Please login to access this submission.'
  dialog_options:
    narrow:
      title: Narrow
    normal:
      title: عادی
    wide:
      title: Wide
element:
  default_more_title: More
file:
  file_private_redirect_message: 'Please login to access the uploaded file.'
