settings:
  default_submit_button_label: Submit
  default_reset_button_label: 'إعادة الضبط'
  default_delete_button_label: حذف
  default_preview_next_button_label: Preview
  default_preview_label: Preview
  dialog_options:
    normal:
      title: Normal
    wide:
      title: Wide
element:
  default_more_title: المزيد
