settings:
  default_submit_button_label: Submit
  default_reset_button_label: 'إعادة الضبط'
  default_delete_button_label: حذف
  default_form_access_denied_message: 'Please login to access this form.'
  default_wizard_start_label: البداية
  default_wizard_confirmation_label: تام
  default_preview_next_button_label: Preview
  default_preview_label: Preview
  default_submission_access_denied_message: 'Please login to access this submission.'
  dialog_options:
    normal:
      title: طبيعي
    wide:
      title: Wide
element:
  default_more_title: المزيد
file:
  file_private_redirect_message: 'Please login to access the uploaded file.'
