_core:
  default_config_hash: PipyKPJHaHaJB3D4LeRoRJxSSd7QbBM0gb5wpSrEFfc
mode: simple
ignored_config_entities:
  - elasticsearch_connector.cluster.infofinland
  - 'next.next_site.*'
  - next.settings
  - update.settings
