_core:
  default_config_hash: QdiqmcH9tjpstXqCQKv4G4rHYE4HjWLFkVzyqooqEWM
favicon:
  mimetype: image/vnd.microsoft.icon
  path: themes/custom/infofinland/favicon.ico
  use_default: false
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: false
logo:
  path: themes/custom/infofinland/logo.svg
  use_default: false
third_party_settings:
  shortcut:
    module_link: true
preset_accent_color: blue
preset_focus_color: gin
enable_darkmode: '0'
classic_toolbar: horizontal
secondary_toolbar_frontend: false
high_contrast_mode: false
accent_color: ''
focus_color: ''
layout_density: ''
show_description_toggle: false
show_user_theme_settings: false
icon_default: true
icon_path: ''
