_core:
  default_config_hash: Cq0qEqvsPlEVfrCpF0VRzK4MFQhRHzqncneoTEKHXUc
delete_newer: false
node_revision_delete_cron: 100
node_revision_delete_time: 3600
node_revision_delete_minimum_age_to_delete_time:
  max_number: 5
  time: days
node_revision_delete_when_to_delete_time:
  max_number: 5
  time: days
