settings:
  default_submit_button_label: Submit
  default_reset_button_label: Sıfırla
  default_delete_button_label: Sil
  default_form_access_denied_message: 'Please login to access this form.'
  default_wizard_prev_button_label: '< Önceki'
  default_wizard_start_label: Başlangıç
  default_wizard_confirmation_label: Tamam
  default_wizard_toggle_show_label: 'Tümünü göster'
  default_preview_next_button_label: Preview
  default_preview_prev_button_label: '< Önceki'
  default_preview_label: Preview
  default_confirmation_message: '[webform:title] başlıklı forma yeni gönderi girildi.'
  default_submission_access_denied_message: 'Please login to access this submission.'
  dialog_options:
    narrow:
      title: Narrow
    normal:
      title: Normal
    wide:
      title: Wide
element:
  default_more_title: More
file:
  file_private_redirect_message: 'Please login to access the uploaded file.'
