settings:
  default_submit_button_label: Submit
  default_reset_button_label: Sıfırla
  default_delete_button_label: Sil
  default_wizard_prev_button_label: '< Previous'
  default_wizard_start_label: Start
  default_wizard_confirmation_label: Complete
  default_wizard_toggle_show_label: 'Show all'
  default_preview_next_button_label: Preview
  default_preview_prev_button_label: '< Previous'
  default_preview_label: Preview
  default_confirmation_message: 'New submission added to [webform:title].'
  dialog_options:
    narrow:
      title: Narrow
    normal:
      title: Normal
    wide:
      title: Wide
element:
  default_more_title: More
