settings:
  default_form_close_message: 'Sorry… This form is closed to new submissions.'
  default_submit_button_label: Submit
  default_reset_button_label: Сбросить
  default_delete_button_label: Удалить
  default_form_required_label: 'Indicates required field'
  default_wizard_prev_button_label: '< Previous'
  default_wizard_start_label: Start
  default_wizard_confirmation_label: Complete
  default_wizard_toggle_show_label: 'Show all'
  default_wizard_toggle_hide_label: 'Hide all'
  default_preview_next_button_label: Preview
  default_preview_prev_button_label: '< Previous'
  default_preview_label: Preview
  default_preview_title: '[webform:title]: Preview'
  default_preview_message: 'Please review your submission. Your submission is not complete until you press the "Submit" button!'
  default_draft_button_label: 'Save Draft'
  default_confirmation_message: 'New submission added to [webform:title].'
  default_confirmation_back_label: 'Back to form'
  default_submission_label: '[webform_submission:submitted-to]: Submission #[webform_submission:serial]'
  default_submission_access_denied_message: 'Please login to access this submission.'
  default_limit_total_message: 'No more submissions are permitted.'
  default_limit_user_message: 'No more submissions are permitted.'
  dialog_options:
    narrow:
      title: Narrow
    normal:
      title: Normal
    wide:
      title: Wide
element:
  default_more_title: More
  default_section_title_tag: h2
mail:
  default_subject: 'Webform submission from: [webform_submission:source-title]'
  default_body_text: |
    Submitted on [webform_submission:created]
    Submitted by: [webform_submission:user]

    Submitted values are:
    [webform_submission:values]
  default_body_html: |
    <p>Submitted on [webform_submission:created]</p>
    <p>Submitted by: [webform_submission:user]</p>
    <p>Submitted values are:</p>
    [webform_submission:values]
