<?php

/**
 * @file
 * Contains 'helfi_ckeditor' hooks.
 */

declare(strict_types=1);

use Drupal\ckeditor5\Plugin\CKEditor5PluginDefinition;
use Drupal\Core\Asset\AttachedAssetsInterface;

/**
 * Modify the list of available CKEditor 5 plugins.
 *
 * @param array $plugin_definitions
 *   An array of all the existing plugin definitions, passed by reference.
 *
 * @see \Drupal\ckeditor5\Plugin\CKEditor5PluginManager
 */
function helfi_ckeditor_ckeditor5_plugin_info_alter(array &$plugin_definitions): void {
  /** @var Drupal\ckeditor5\Plugin\CKEditor5PluginDefinition $table_plugin_definition */
  $table_plugin_definition = $plugin_definitions['ckeditor5_table'];
  $original_table_plugin = $table_plugin_definition->toArray();

  // Unset the 'table.PlainTableOutput' CKEditor5 plugin as we want to preserve
  // the <figure class="table"> > <figcaption> functionality.
  if (($plugin = array_search('table.PlainTableOutput', $original_table_plugin['ckeditor5']['plugins'])) !== FALSE) {
    unset($original_table_plugin['ckeditor5']['plugins'][$plugin]);
  }

  // Save ckeditor5_table plugin definitions.
  $plugin_definitions['ckeditor5_table'] = new CKEditor5PluginDefinition($original_table_plugin);
}

function helfi_ckeditor_js_settings_alter(array &$settings, AttachedAssetsInterface $assets) {
  $content_language = \Drupal::languageManager()->getCurrentLanguage(\Drupal\Core\Language\LanguageInterface::TYPE_CONTENT);
  $settings['editor']['formats']['full_html']['editorSettings']['language']['ui'] = $content_language->getId();
  $settings['editor']['formats']['simple_html']['editorSettings']['language']['ui'] = $content_language->getId();
}
